services:
  - type: web
    name: educ-analytics
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0